import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">{children}</body>

      <footer id="contact" className="bg-slate-900 text-slate-300">
        <div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 md:grid-cols-3">
          <div>
            <h4 className="text-xl font-bold text-white">MediCare Hospital</h4>
            <p className="mt-4 text-sm leading-6 text-slate-400">
              123 Health Street, Medical City
              <br />
              Phone: +1 (234) 567-890
              <br />
              Email: info@medicarehospital.com
            </p>
          </div>

          <div>
            <h5 className="font-semibold text-white">Quick Links</h5>
            <ul className="mt-4 space-y-2 text-sm">
              <li>
                <a href="#home" className="hover:text-white">
                  Home
                </a>
              </li>
              <li>
                <a href="#department" className="hover:text-white">
                  Department
                </a>
              </li>
              <li>
                <a href="#doctors" className="hover:text-white">
                  Doctors
                </a>
              </li>
              <li>
                <a href="#about" className="hover:text-white">
                  About
                </a>
              </li>
            </ul>
          </div>

          <div>
            <h5 className="font-semibold text-white">Opening Hours</h5>
            <ul className="mt-4 space-y-2 text-sm text-slate-400">
              <li>Mon - Fri: 8:00 AM - 8:00 PM</li>
              <li>Saturday: 9:00 AM - 5:00 PM</li>
              <li>Sunday: Emergency Only</li>
            </ul>
          </div>
        </div>

        <div className="border-t border-slate-800 py-4 text-center text-sm text-slate-500">
          © 2026 MediCare Hospital. All rights reserved.
        </div>
      </footer>
    </html>
  );
}
